name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up the environment for Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.6'
    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint
    - name: Run linter
      run: golint .
