name: Test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up the environment for Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.6'
    - name: Install dependencies
      run: |
        go get github.com/magefile/mage
        go install github.com/magefile/mage
    - name: Run unit tests
      run: mage test:unit
